### ISSUE TITLE
When zooming the satellite tiles appear to move around

### ISSUE THREAD

**Issue by drewpotter** [anselm/aterrain#12]
Hi,

Thanks for this project! I noticed that when I zoom in and out of the globe it appears that the various continents actually move up and down on the globe. I don't know whether there is a glitch with the tiles somehow?

If necessary I can link a video here to show what is happening.

Best regards,

Andrew

**Comment by drewpotter** [comment]
Here is a video of the issue; https://photos.app.goo.gl/nWRLmoiYbStOFSQu2

**Comment by anselm** [comment]
That was definitely a horrible horrible issue. What was going on was that the tiles were being read and rendered directly. But they are in a Mercator projection. I had to write a CPU based reverse-mercator projection to correct this - see ImageServer.js. It is fixed now.

**Comment by anselm** [comment]
This is the fix https://github.com/anselm/aterrain/commit/ce4cfddb32ee9fa73cda19dd40a731e677ab7137

**Comment by drewpotter** [comment]
Brilliant work! Thanks for fixing this!
